using System;
using CleanItERP.Model;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CleanItERPTests.Model
{
    public class NavigationPropertiesTest : IDisposable
    {

        private SqliteConnection Connection { get; }
        private DbContextOptions<CleanItERPContext> ContextOptions {get;} 

        public NavigationPropertiesTest()
        {
            Connection = new SqliteConnection("DataSource=:memory:");
            Connection.Open();

            ContextOptions = new DbContextOptionsBuilder<CleanItERPContext>()
                .UseSqlite(Connection)
                .Options;

            using(var context = new CleanItERPContext(ContextOptions)){
                context.Database.EnsureCreated();
            }
        }
        public void Dispose()
        {
            Connection.Close();
        }

        [Fact]
        public void TestUserRoleNavOfUser() {
            var userRole = EntityFactory.CreateUserRole();
            var user = new User(){
                Name = "TestUser",
                UserRole = userRole
            };

            using(var context = CreateContext()){
                context.Add(user);
                context.SaveChanges();
            }

            userRole.Id.Should().BeAutoGeneratedId();
            user.UserRoleId.Should().Be(userRole.Id);
        }

        private CleanItERPContext CreateContext() => new CleanItERPContext(ContextOptions);



    }
}