using FluentAssertions;
using FluentAssertions.Numeric;

namespace CleanItERPTests.Model
{
    public static class NumericAssertionsExtensions
    {
        public static AndConstraint<NumericAssertions<int>> BeAutoGeneratedId(this NumericAssertions<int> assertion){
            return assertion.BeGreaterThan(0);
        }
    }
}